version: '3'

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=clean-arch-java-demo
      - POSTGRES_USER=clean-arch-java-demo
      - POSTGRES_PASSWORD=clean-arch-java-demo
    networks:
      - custom

  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
      - "8883:8883"
    environment:
      STUBBY_PORT: 8883
    volumes:
      - ./data/stubby/integrations.yml:/usr/local/stubby.yml
    networks:
      - custom

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.165.70.0/16
