databaseChangeLog:
  - changeSet:
      id: 20200805013000-1
      author: mateus.cruz
      comment: "Create table customers"
      changes:
        - createTable:
            tableName: customers
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  autoIncrement: false
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: birth_date
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: city
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: cpf
                  type: varchar(16)
                  constraints:
                    nullable: false
